name: Deploy Project
on:
  push:
    branches: [master, 'releases/**'] # Only pushes to main and releases branch trigger the workflow.
    paths-ignore:
      - '.github/workflows/*' # Ignore changes to the test workflow file.
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run typecheck
        run: npm run typecheck
      - name: Run tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            .next
            package.json
            package-lock.json
            
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy project
        run: echo "Deploying project..."
