name: Notify Workflow Status
on:
  workflow_run:
    workflows: ['Deploy Project', 'Test Project']
    types:
      - completed
jobs:
  detect-status:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Workflow Status
        run: |
          case "${{ github.event.workflow_run.conclusion }}" in
            success) echo "✅ Workflow completed successfully!" ;;
            failure) echo "❌ Workflow failed!" ;;
            cancelled) echo "⚠️ Workflow was canceled!" ;;
            *) echo "Unknown status: ${{ github.event.workflow_run.conclusion }}" ;;
          esac
