name: Test Project
on:
  push:
    branches: [master, 'releases/**'] # Only pushes to main and releases branch trigger the workflow.
    paths-ignore:
      - '.github/workflows/*' # Ignore changes to the test workflow file.
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run typecheck
        run: npm run typecheck
      - name: Run tests
        run: npm run test
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-files
          path: ${{ github.workspace }}/coverage
          if-no-files-found: error
          include-hidden-files: true
